Add an option to pause before exit in case of error

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-set -eu
+set -euE
 set -o pipefail
 
 # Library of functions for the kayobe development environment.
@@ -48,6 +48,11 @@ function config_defaults {
     export KAYOBE_EXTRA_ARGS=${KAYOBE_EXTRA_ARGS:-}
 
     export KAYOBE_AUTOMATION_LOG_LEVEL=${KAYOBE_AUTOMATION_LOG_LEVEL:-warn}
+    # When to pause execution. This is useful for debugging. Can be one of:
+    #   - on-error
+    # You must run the script with errtrace (-E) if using errexit (-e) for the
+    # on-error trap to function.
+    export KAYOBE_AUTOMATION_BREAK=${KAYOBE_AUTOMATION_BREAK:-}
 
     # Log directory in case of errors
     export LOGDIR=${LOGDIR:-/tmp/logs}
@@ -440,6 +445,16 @@ function is_absolute_path {
     esac
 }
 
+##############################################################################
+# Traps
+
+function on_error {
+  if [ ${KAYOBE_AUTOMATION_BREAK:-invalid,,} == "on-error" ]; then
+    log_error "An error occured, pausing to allow debug access"
+    pause
+  fi
+}
+
 ###############################################################################
 # Installation
 
@@ -591,6 +606,7 @@ function pull_request {
 }
 
 function kayobe_init {
+    trap on_error ERR
     call_with_hooks config_init
     call_with_hooks validate
     call_with_hooks environment_diagnostics
